[[StarPU]]
arch = "aarch64"
git-tree-sha1 = "2f08b18f50d79f347f85af388c883217a3316511"
libgfortran_version = "5.0.0"
os = "macos"

    [[StarPU.download]]
    sha256 = "1b2e0bd3c0fed6d0a9661f75b28b333d6ac42f000884bae9095f9bd9624b6def"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.aarch64-apple-darwin-libgfortran5.tar.gz"
[[StarPU]]
arch = "aarch64"
git-tree-sha1 = "552c6039b36d4d8ef3e492f772a321bb0ec56356"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "b8c5b7c4c3a12d5404b9e0cad1a0d83e585e789e6deb491d2fcff8a10c23752e"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.aarch64-linux-gnu-libgfortran3.tar.gz"
[[StarPU]]
arch = "aarch64"
git-tree-sha1 = "4baf23e91a992a2c1e995f63fff88a987257c207"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "b5aa1a7005094507073da5d0472882971d39a1a123df813989775007cc564c4d"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.aarch64-linux-gnu-libgfortran4.tar.gz"
[[StarPU]]
arch = "aarch64"
git-tree-sha1 = "2b448b38ade40a3e66245685ab2daa7e0eb24183"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "4b814e906ddf772d08817e954cc38e8fab837b3cdb958532151ba0615da15729"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.aarch64-linux-gnu-libgfortran5.tar.gz"
[[StarPU]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8764ca71bb41ccfb4d424de1d912890ce6013249"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "a0c923ebe4eb2f1fab6107ab5b46e53baa79be7ce68e6296e6081d42b66ceba2"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[StarPU]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "afe94bfd29afaa5687ffe6727fc79015309503e2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "94225a76bb25de5e2e2d79ac525564ada071f98e17c635abf55d0d9bcd8a53d9"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[StarPU]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "055a9e69df0f861d73315458d27b58474b2e2695"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "a6079a77bca3806aee24811705459e1af182acee0bc1c5193f97549fd149f36b"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[StarPU]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e4b4f14a15631dbfb21d36883cfecdf05da74228"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "9a38a6a138787a0ca72d5f607a2ac366fa8702d4232f858eb14613d643fa05c3"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[StarPU]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a974b2c1a819bf95504683a046538260da4c0fcc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "0e706ced7087cb35632f477a32a4e3cfb3dc840cc97d2c6063b37f4c8a4db98a"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[StarPU]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5dfc8fbe580de4b2a7341b5b0db182337c0d6ba1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "912cef860e5a5b4e80db13d6ac14c0e6c2a364f8564ad8bad9cac04da5c7ffcd"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[StarPU]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3ba9fa5824ec3e55f67626989572c9a1c35c6b77"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "a112fe04aabc82fcbc5380c313db3213ac85fcea2d63d4d9bc1bfcba7e548ec7"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[StarPU]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c3ef436e39ab6663c0ce3e4ba4f756f7968d2b65"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "ba86246565b86bcd30e20f5a129f34f60e5c04b34509d8ab906be40312d017b1"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[StarPU]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b5ad6754fbdd40db914c68dd2108e1e2ca9179e4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "507d9c47e501b09fbdc1769a798543cab3728d43609cae43a48e54ca8ed60bb9"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[StarPU]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b234303e8d9c33e679a50b01fd204ec8f96cfb05"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "eb4d484d1ac8ca0bb0a58225da03b99a10bac5d9a58deda3cebad26fc7971871"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[StarPU]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "662a6d8160f97f1e4c86e19a30eaab20e451b70b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "8fbbfc9b0104789f0f5c0261fd1aad146052791425ee9b3d7597da4d2e6caecf"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[StarPU]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "db74fed3dfdf1b190b0e41eca95d166a1bb14c7a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "2b3c11c35ad17d9838b2721ab0e0406f8cbc8e1305131e8d8ad537afa951a620"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[StarPU]]
arch = "i686"
git-tree-sha1 = "61bfac076955c7fbe2b7c3f00e22ef90c1fff44e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "c1391923f3c478adb47bbcdd6677ff420d48fdb0f08cf80595377c1f4cb2d892"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.i686-linux-gnu-libgfortran3.tar.gz"
[[StarPU]]
arch = "i686"
git-tree-sha1 = "ab1c22cda5a88a6eaccbd5022c73ec4d145d99be"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "0aa3fa273143c87537d0134f1deb7c7c13f2a8892fd75358dc233fab18d63920"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.i686-linux-gnu-libgfortran4.tar.gz"
[[StarPU]]
arch = "i686"
git-tree-sha1 = "a01b0f63b426d75d94cbd60d7105cb250a469e70"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "7c087ab675cbe4ad21c735e327dfd5e1e796eab37cc4c0f33a776b4872ae56b7"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.i686-linux-gnu-libgfortran5.tar.gz"
[[StarPU]]
arch = "i686"
git-tree-sha1 = "4cc4afbbf27eadd572aed05fd47f20a8b82585ff"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "4ca02eb396856f8e330009ec9c2b9ca2a5cfaaa7073b42aa907dd2a00d4a9262"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.i686-linux-musl-libgfortran3.tar.gz"
[[StarPU]]
arch = "i686"
git-tree-sha1 = "bb60763f29c2677f89550c2e6a7782695ed13529"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "8a3196e3dcfeb81e5f42b5ad39975b9b29009c0fafac6796ab2580f2b3d8c905"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.i686-linux-musl-libgfortran4.tar.gz"
[[StarPU]]
arch = "i686"
git-tree-sha1 = "3f6dfb6fbff331bd232970f5e900540059817688"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "f3a5fa3abff02470eec2a5a4141c746a2c807b774c7f2925d5f890e8cb8905ed"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.i686-linux-musl-libgfortran5.tar.gz"
[[StarPU]]
arch = "i686"
git-tree-sha1 = "b6498eecaa93b080e2eb19b1f25d3b7566d0975e"
libgfortran_version = "3.0.0"
os = "windows"

    [[StarPU.download]]
    sha256 = "4960391bac44612c866ff0991ce888b75d4af857d10dab9dc73744a413bc54c4"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.i686-w64-mingw32-libgfortran3.tar.gz"
[[StarPU]]
arch = "i686"
git-tree-sha1 = "833922b153a84b4c8e45ce7aca24820c2ddb6ef2"
libgfortran_version = "4.0.0"
os = "windows"

    [[StarPU.download]]
    sha256 = "806925630039e3d9359d6520895b897391a1024171cad27502b1b2e5d088cc3d"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.i686-w64-mingw32-libgfortran4.tar.gz"
[[StarPU]]
arch = "i686"
git-tree-sha1 = "ddddf064097a012ba5ff1d0ed73186816efaff54"
libgfortran_version = "5.0.0"
os = "windows"

    [[StarPU.download]]
    sha256 = "5f14ebe259c8b79bce4e0b4a32ccc8d285f936196d71d5848205c9cb7f62f87e"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.i686-w64-mingw32-libgfortran5.tar.gz"
[[StarPU]]
arch = "powerpc64le"
git-tree-sha1 = "68c672464ce73ea841aa077c121103c1d6e588f4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "606c61ad71db34586c8515852d72670e837e789a8882949fa68e0c67d05af1f8"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[StarPU]]
arch = "powerpc64le"
git-tree-sha1 = "9db742c085dfd9bfd3ead4caef796bcdddec37b7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "c6fc5255f4395765086d37f77b2f5f4169598245ea838e9a66b478d3241a0f5f"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[StarPU]]
arch = "powerpc64le"
git-tree-sha1 = "80d3054fbe55f391d8c248a0a77ba4d7bcae27e0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "c5a8e1702f96bc802fb3c6887b587d577b9f14de394738999e6ea885ffa2018a"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[StarPU]]
arch = "x86_64"
git-tree-sha1 = "9b7d232b3dfb9ee9fda550868677e6f384e87e69"
libgfortran_version = "3.0.0"
os = "macos"

    [[StarPU.download]]
    sha256 = "a013527ef93b3da6dccdcf3827d458a3b0fd43ede0932d99b7c37cc2dc46ee95"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.x86_64-apple-darwin-libgfortran3.tar.gz"
[[StarPU]]
arch = "x86_64"
git-tree-sha1 = "9b7d232b3dfb9ee9fda550868677e6f384e87e69"
libgfortran_version = "4.0.0"
os = "macos"

    [[StarPU.download]]
    sha256 = "a013527ef93b3da6dccdcf3827d458a3b0fd43ede0932d99b7c37cc2dc46ee95"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.x86_64-apple-darwin-libgfortran4.tar.gz"
[[StarPU]]
arch = "x86_64"
git-tree-sha1 = "9b7d232b3dfb9ee9fda550868677e6f384e87e69"
libgfortran_version = "5.0.0"
os = "macos"

    [[StarPU.download]]
    sha256 = "a013527ef93b3da6dccdcf3827d458a3b0fd43ede0932d99b7c37cc2dc46ee95"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.x86_64-apple-darwin-libgfortran5.tar.gz"
[[StarPU]]
arch = "x86_64"
git-tree-sha1 = "4710a218aa3f87f842a897c91840bf240afe48fb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "93ddd4e4bbe77975a0adc144a219499cfbbb123b46e0d6e12b80a1117dd17849"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.x86_64-linux-gnu-libgfortran3.tar.gz"
[[StarPU]]
arch = "x86_64"
git-tree-sha1 = "25b0d32f45f1a40d4834b0c7cb09cf26f4b5a90d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "9e1c410194409bc86b5cf9083c2622623d86a8b47427ea01850f570391d2a0f3"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.x86_64-linux-gnu-libgfortran4.tar.gz"
[[StarPU]]
arch = "x86_64"
git-tree-sha1 = "d2b1f222063d63d2fac81eef9b3668d8b0f2bfdf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "f16e73b762217ada0b07acf1b9d0f3e109be73532ec9f7f471ea798a0348d3d9"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.x86_64-linux-gnu-libgfortran5.tar.gz"
[[StarPU]]
arch = "x86_64"
git-tree-sha1 = "98ed234a377f45ead5e38697d6354ce04ada7b42"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "3856d9ad7aae979edc73d74f78e0720ccb6a76894f2ab12a5503c70520a71b99"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.x86_64-linux-musl-libgfortran3.tar.gz"
[[StarPU]]
arch = "x86_64"
git-tree-sha1 = "bffa3be9e32d106f93b7693eedab71e1592120bc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "b771223c31cb44ba4945c8618596f46fab368a72530d7c2247c10dc5585c5c45"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.x86_64-linux-musl-libgfortran4.tar.gz"
[[StarPU]]
arch = "x86_64"
git-tree-sha1 = "1da7d49ffc70c6d894fc39eb5b0bed743fe4bb55"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[StarPU.download]]
    sha256 = "af87180ba33e168d61e5231c0f532acdc8e79418878761e00c9a6d5a19d14eeb"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.x86_64-linux-musl-libgfortran5.tar.gz"
[[StarPU]]
arch = "x86_64"
git-tree-sha1 = "513c241052beea6e0630c1dd3f3cf8e5b68da9b2"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[StarPU.download]]
    sha256 = "40455cff939e7f9262938cfc3b8e4c66d48759de44463e0f0e6c4968a52055a7"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[StarPU]]
arch = "x86_64"
git-tree-sha1 = "f433021151e210d4765632544051d4c09b2b0890"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[StarPU.download]]
    sha256 = "87062c010fbb0846dea3b2060118c3b5872e977169ab5890c5921593c358d4a5"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[StarPU]]
arch = "x86_64"
git-tree-sha1 = "77f6916141ffeda42cba8e5ef9204bc0bf17a340"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[StarPU.download]]
    sha256 = "fa3efe84b3ab8057d9e5b9c58318d24c8552cc7007c15435cc2825240053b3ec"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[StarPU]]
arch = "x86_64"
git-tree-sha1 = "64a01a26f8d320d6958baea768d7bde01526cbd2"
libgfortran_version = "3.0.0"
os = "windows"

    [[StarPU.download]]
    sha256 = "29a4874a90c89920e3cccac51e50281c0907a7f3f67fb32f6e1143eaf3136c05"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[StarPU]]
arch = "x86_64"
git-tree-sha1 = "5d167cfe8eceaf1bf04d66d44e6763b28b4db4fd"
libgfortran_version = "4.0.0"
os = "windows"

    [[StarPU.download]]
    sha256 = "477bd09daac57c915e8bc73a9c72eefa22afb444c899f7eebf0f4dc86d06b996"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[StarPU]]
arch = "x86_64"
git-tree-sha1 = "6dd7d95391570d966e2236c865ddfa504bd7ecb2"
libgfortran_version = "5.0.0"
os = "windows"

    [[StarPU.download]]
    sha256 = "152b6793b9f32947e64196f634b78a0e6c73ac3779a1476ae3328a702100956d"
    url = "https://github.com/JuliaBinaryWrappers/StarPU_jll.jl/releases/download/StarPU-v1.3.9+0/StarPU.v1.3.9.x86_64-w64-mingw32-libgfortran5.tar.gz"
